RentalMVC2010/RentalMobile/Models/TenantMaintenance.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalMobile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TenantMaintenance
    {
        public int TenantID { get; set; }
        public int MaintenanceID { get; set; }
    
        public virtual MaintenanceOrder MaintenanceOrder { get; set; }
    }
}

RentalMVC2010/RentalMobile/Controllers/MaintenancePhotoGalleryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RentalMobile.Models;

namespace RentalMobile.Controllers
{
    public class MaintenancePhotoGalleryController : Controller
    {
        private readonly DB_33736_rentalEntities db = new DB_33736_rentalEntities();

        public JsonResult GetJsonData()
        {
            //var persons = new List<Person>
            //                  {
            //                      new Person{Id = 1, FirstName = "F1", 
            //                          LastName = "L1", 
            //                          Addresses = new List<Address>
            //                                          {
            //                                              new Address{Line1 = "LaneA"},
            //                                              new Address{Line1 = "LaneB"}
            //                                          }},

            //                      new Person{Id = 2, FirstName = "F2", 
            //                          LastName = "L2", 
            //                          Addresses = new List<Address>
            //                                          {
            //                                              new Address{Line1 = "LaneC"},
            //                                              new Address{Line1 = "LaneD"}
            //                                          }}};

            var persons = db.MaintenancePhotoes.ToList();
            var p = persons.Select(d => new Photo {PhotoID = d.PhotoID, PathPath = d.PhotoPath}).ToList();



            foreach (var ph in p)
            {
                ph.PathPath = ph.PathPath.Replace(@"~\Photo", @"../../Photo").Replace("\\", "/");
            }
            //foreach (var i in p)
                //{
                //    i.PathPath.Replace(oldValue: @"~\Photo", newValue: @"../../Photo");
                //    i.PathPath.Replace(oldValue: "Photo", newValue: "image");
                //}
            return Json( p, JsonRequestBehavior.AllowGet);
        }

        public JsonResult PopulateDetails(int id)
        {
            var a = db.MaintenancePhotoes.ToList();
            return Json(a, JsonRequestBehavior.AllowGet);
        }


        public ViewResult Json()
        {
            return View();
        }

        //public JsonResult PopulateDetails(int id)
        //{
        //    //userResultModel.LastName = user.LastName;
        //    //userResultModel.FirstName = user.FirstName;
        //    //userResultModel.Message = String.Empty; //success message is empty in this case

        //    MaintenancePhoto maintenancephoto = db.MaintenancePhotoes.Find(35);
        //   // IQueryable<MaintenancePhoto> maintenancephoto = db.MaintenancePhotoes.Where(o => o.MaintenanceID == 35);
        //    return Json(maintenancephoto, JsonRequestBehavior.AllowGet);
        //}



        //
        // GET: /MaintenancePhotoGallery/












        public ViewResult Index()
        {
            var maintenancephotoes = db.MaintenancePhotoes.Include(m => m.MaintenanceOrder);
            return View(maintenancephotoes.ToList());
        }


        public ViewResult Details(int id)
        {
            MaintenancePhoto maintenancephoto = db.MaintenancePhotoes.Find(id);
            return View(maintenancephoto);
        }


        public ActionResult Create()
        {
            ViewBag.MaintenanceID = new SelectList(db.MaintenanceOrders, "MaintenanceID", "Description");
            return View();
        }


        [HttpPost]
        public ActionResult Create(MaintenancePhoto maintenancephoto)
        {
            if (ModelState.IsValid)
            {
                db.MaintenancePhotoes.Add(maintenancephoto);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MaintenanceID = new SelectList(db.MaintenanceOrders, "MaintenanceID", "Description",
                                                   maintenancephoto.MaintenanceID);
            return View(maintenancephoto);
        }


        public ActionResult Edit(int id)
        {
            MaintenancePhoto maintenancephoto = db.MaintenancePhotoes.Find(id);
            ViewBag.MaintenanceID = new SelectList(db.MaintenanceOrders, "MaintenanceID", "Description",
                                                   maintenancephoto.MaintenanceID);
            return View(maintenancephoto);
        }


        [HttpPost]
        public ActionResult Edit(MaintenancePhoto maintenancephoto)
        {
            if (ModelState.IsValid)
            {
                db.Entry(maintenancephoto).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaintenanceID = new SelectList(db.MaintenanceOrders, "MaintenanceID", "Description",
                                                   maintenancephoto.MaintenanceID);
            return View(maintenancephoto);
        }


        public ActionResult Delete(int id)
        {
            MaintenancePhoto maintenancephoto = db.MaintenancePhotoes.Find(id);
            return View(maintenancephoto);
        }


        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            MaintenancePhoto maintenancephoto = db.MaintenancePhotoes.Find(id);
            db.MaintenancePhotoes.Remove(maintenancephoto);
            db.SaveChanges();
            return RedirectToAction("Index", "TenantMaintenance");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }






























    public class Person
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }

        public List<Address> Addresses { get; set; }
    }

    public class Address
    {
        public string Line1 { get; set; }
        public string Line2 { get; set; }
        public string ZipCode { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
    }

    public class Photo
    {
        public int PhotoID { get; set; }
        public string PathPath { get; set; }
    }
}

RentalMVC2010/RentalMobile/Controllers/TenantMaintenanceController.cs
using System;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using System.Web.Security;
using RentalMobile.Helpers;
using RentalMobile.Models;

namespace RentalMobile.Controllers
{ 
    public class TenantMaintenanceController : Controller
    {
        private readonly DB_33736_rentalEntities _db = new DB_33736_rentalEntities();

        public ViewResult Index()
        {
            var maintenanceorders = _db.MaintenanceOrders.Include(m => m.ServiceType).Include(m => m.UrgencyType);
             var userGUID = UserHelper.GetUserGUID();
            if (userGUID == null)
            {
                return View(maintenanceorders.ToList());
            }
            var tenantID = UserHelper.GetTenantID((Guid) userGUID);
            maintenanceorders = _db.MaintenanceOrders.Include(m => m.ServiceType).Include(m => m.UrgencyType).
                Where(t => t.TenantMaintenance.TenantID == tenantID);
            return View(maintenanceorders.ToList());
        }

        public ViewResult Details(int id)
        {
            var maintenanceorder = _db.MaintenanceOrders.Find(id);
            return View(maintenanceorder);
        }

        public ActionResult Create()
        {
            ViewBag.ServiceTypeID = new SelectList(_db.ServiceTypes, "ServiceTypeID", "ServiceType1");
            ViewBag.UrgencyID = new SelectList(_db.UrgencyTypes, "UrgencyTypeID", "UrgencyType1");
            return View();
        }

        [HttpPost]
        public ActionResult Create([Bind(Exclude = "MaintenanceID")]MaintenanceOrder maintenanceorder)
        {
            if (ModelState.IsValid)
            {
                _db.MaintenanceOrders.Add(maintenanceorder);
                _db.SaveChanges();
                var userGUID = UserHelper.GetUserGUID();
                if (userGUID != null)
                {
                    var tenantID = UserHelper.GetTenantID((Guid) userGUID);
                    if (tenantID != null)
                    {
                        var tenantMaintenance = new TenantMaintenance
                                                    {
                                                        TenantID = (int) tenantID,
                                                        MaintenanceID = maintenanceorder.MaintenanceID,
                                                        MaintenanceOrder = maintenanceorder
                                                    };
                        _db.TenantMaintenances.Add(tenantMaintenance);
                    }
                }
                _db.SaveChanges();
                TempData["UserName"] = Membership.GetUser(System.Web.HttpContext.Current.User.Identity.Name);
                TempData["Id"] = maintenanceorder.MaintenanceID;
                TempData["Type"] = "Requests";
                return RedirectToAction("Index", "UploadMaintenancePhoto");
            }

            ViewBag.ServiceTypeID = new SelectList(_db.ServiceTypes, "ServiceTypeID", "ServiceType1", maintenanceorder.ServiceTypeID);
            ViewBag.UrgencyID = new SelectList(_db.UrgencyTypes, "UrgencyTypeID", "UrgencyType1", maintenanceorder.UrgencyID);
            return View(maintenanceorder);
        }

        public ActionResult Edit(int id)
        {
            MaintenanceOrder maintenanceorder = _db.MaintenanceOrders.Find(id);
            ViewBag.ServiceTypeID = new SelectList(_db.ServiceTypes, "ServiceTypeID", "ServiceType1", maintenanceorder.ServiceTypeID);
            ViewBag.UrgencyID = new SelectList(_db.UrgencyTypes, "UrgencyTypeID", "UrgencyType1", maintenanceorder.UrgencyID);
            return View(maintenanceorder);
        }

        [HttpPost]
        public ActionResult Edit(MaintenanceOrder maintenanceorder)
        {
            if (ModelState.IsValid)
            {
                _db.Entry(maintenanceorder).State = EntityState.Modified;
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ServiceTypeID = new SelectList(_db.ServiceTypes, "ServiceTypeID", "ServiceType1", maintenanceorder.ServiceTypeID);
            ViewBag.UrgencyID = new SelectList(_db.UrgencyTypes, "UrgencyTypeID", "UrgencyType1", maintenanceorder.UrgencyID);
            return View(maintenanceorder);
        }

        public ActionResult Delete(int id)
        {
            MaintenanceOrder maintenanceorder = _db.MaintenanceOrders.Find(id);
            return View(maintenanceorder);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            MaintenanceOrder maintenanceorder = _db.MaintenanceOrders.Find(id);
            TenantMaintenance tenantmaintenance = _db.TenantMaintenances.FirstOrDefault(x => x.MaintenanceID == id);
            _db.MaintenanceOrders.Remove(maintenanceorder);
            _db.TenantMaintenances.Remove(tenantmaintenance);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult AddMorePhotos([Bind(Exclude = "MaintenanceID")]MaintenanceOrder maintenanceorder)
        {
            TempData["UserName"] = Membership.GetUser(System.Web.HttpContext.Current.User.Identity.Name);
            TempData["Id"] = maintenanceorder.MaintenanceID;
            TempData["Type"] = "Requests";
            return RedirectToAction("Index", "AddMaintenancePhoto");
        }

        protected override void Dispose(bool disposing)
        {
            _db.Dispose();
            base.Dispose(disposing);
        }

    }
}

RentalMVC2010/RentalMobile/Views/TenantMaintenance/Create.cshtml
@model RentalMobile.Models.MaintenanceOrder
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/Template/_ConceptLayoutPage.cshtml";
}
<h2>
    Create</h2>
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>MaintenanceOrder</legend>
         @Html.LabelFor(model => model.MaintenanceID)
        <div class="editor-label">
            @Html.LabelFor(model => model.UnitID)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.UnitID)
            @Html.ValidationMessageFor(model => model.UnitID)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.MaintenanceDate)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.MaintenanceDate)
            @Html.ValidationMessageFor(model => model.MaintenanceDate)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.UrgencyID, "UrgencyType")
        </div>
        <div class="editor-field">
            @Html.DropDownList("UrgencyID", String.Empty)
            @Html.ValidationMessageFor(model => model.UrgencyID)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.ServiceTypeID, "ServiceType")
        </div>
        <div class="editor-field">
            @Html.DropDownList("ServiceTypeID", String.Empty)
            @Html.ValidationMessageFor(model => model.ServiceTypeID)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.PetsinUnit)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.PetsinUnit)
            @Html.ValidationMessageFor(model => model.PetsinUnit)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.TenantPresence)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.TenantPresence)
            @Html.ValidationMessageFor(model => model.TenantPresence)
        </div>
        @*<form action="#" class="sixteen columns shadded wide-on-small-screen">

    <ul class="grid-form fourteen columns push by-one remove-bottom">
        <li class="four columns alpha">
            <label for="prop-type-field" class="screen-reader-text">Property type</label>
            <input id="prop-type-field" type="text" placeholder="Property type" required />
        </li>
        <li class="four columns">
            <label for="address-field" class="screen-reader-text">Address</label>
            <input id="address-field" type="text" placeholder="Address" required />
        </li>
        <li class="three columns relative">
            <label for="beds-select" class="screen-reader-text">Beds</label>
            <select id="beds-select" class="custom-select" title="Beds">
                <option value="1">Beds</option>
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5">5</option>
            </select>
        </li>
        <li class="three columns omega relative">
            <label for="baths-select" class="screen-reader-text">Baths</label>
            <select id="baths-select" class="custom-select" title="Baths">
                <option value="1">Baths</option>
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5">5</option>
            </select>
        </li>
					
        <li class="four columns alpha">
            <label for="features-field" class="screen-reader-text">Features</label>
            <input id="features-field" type="text" placeholder="Features" required />
        </li>
        <li class="five columns">	
            <label for="date-available-field" class="screen-reader-text">Date Available</label>
            <input id="date-available-field" type="text" placeholder="Date Available" required />
        </li>
        <li class="five columns omega">
            <label for="photo-field" class="screen-reader-text">Upload photo</label>
            <input id="photo-field" type="text" placeholder="Upload photo" class="upload-field" />
        </li>

        <li class="four columns alpha">
            <label for="price-field" class="screen-reader-text">Price</label>
            <input id="price-field" type="text" placeholder="Price" required />
        </li>
        <li class="three columns">	
            <label for="meters-field" class="screen-reader-text">Meters</label>
            <input id="meters-field" type="text" placeholder="Meters" required />
        </li>
        <li class="four columns">
            <label for="style-field" class="screen-reader-text">Building style</label>
            <input id="style-field" type="text" placeholder="Building style" required />
        </li>
        <li class="three columns omega">
            <label for="built-field" class="screen-reader-text">Year built</label>
            <input id="built-field" type="text" placeholder="Year built" />
        </li>

        <li class="five columns alpha">	
            <label for="name-field" class="screen-reader-text">Your name</label>
            <input id="name-field" type="text" placeholder="Your name" required />
        </li>
        <li class="five columns">
            <label for="last-name-field" class="screen-reader-text">Last name</label>
            <input id="last-name-field" type="text" placeholder="Last name" required />
        </li>
        <li class="four columns omega">
            <label for="email-field" class="screen-reader-text">Year built</label>
            <input id="email-field" type="email" placeholder="Email" />
        </li>

        <li class="fourteen columns alpha omega">
            <label for="description-field" class="screen-reader-text">Description</label>
            <textarea name="description-field" id="description-field" rows="20" placeholder="Description" class="full-width"></textarea>
        </li>

        <li class="two columns omega push by-twelve">		
            <input type="submit" value="SEND IT" class="tall"/>
        </li>
    </ul>

</form>*@
        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

RentalMVC2010/RentalMobile/Views/TenantMaintenance/Delete.cshtml
@model RentalMobile.Models.MaintenanceOrder

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>MaintenanceOrder</legend>

@*    <div class="display-label">MaintenanceID</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.MaintenanceID)
    </div>
*@
    <div class="display-label">UnitID</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.UnitID)
    </div>

    <div class="display-label">MaintenanceDate</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.MaintenanceDate)
    </div>

    <div class="display-label">UrgencyType</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.UrgencyType.UrgencyType1)
    </div>

    <div class="display-label">Description</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Description)
    </div>

    <div class="display-label">ServiceType</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ServiceType.ServiceType1)
    </div>

    <div class="display-label">PetsinUnit</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.PetsinUnit)
    </div>

    <div class="display-label">TenantPresence</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.TenantPresence)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

RentalMVC2010/RentalMobile/Views/TenantMaintenance/Details.cshtml
@model RentalMobile.Models.MaintenanceOrder

@{
    ViewBag.Title = "Home Page";
    Layout = "~/Views/Shared/Template/_ConceptLayoutPage.cshtml";
}

<h2>Details</h2>
<fieldset>
    <legend>MaintenanceOrder</legend>

    <div class="display-label">UnitID</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.UnitID)
    </div>

    <div class="display-label">MaintenanceDate</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.MaintenanceDate)
    </div>

    <div class="display-label">UrgencyType</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.UrgencyType.UrgencyType1)
    </div>

    <div class="display-label">Description</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Description)
    </div>

    <div class="display-label">ServiceType</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ServiceType.ServiceType1)
    </div>

    <div class="display-label">PetsinUnit</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.PetsinUnit)
    </div>

    <div class="display-label">TenantPresence</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.TenantPresence)
    </div>
</fieldset>









<div>

@Html.Partial("_MaintenancePhotoGalleryList", Model.MaintenancePhotoes)

</div>


<p>
    @Html.ActionLink("Edit", "Edit", new { /* id=Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

RentalMVC2010/RentalMobile/Views/TenantMaintenance/Edit.cshtml
@model RentalMobile.Models.MaintenanceOrder
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/Template/_ConceptLayoutPage.cshtml";
}
<h2>
    Edit</h2>
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>MaintenanceOrder</legend>@*        <div class="editor-label">
            @Html.LabelFor(model => model.MaintenanceID)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.MaintenanceID)
            @Html.ValidationMessageFor(model => model.MaintenanceID)
        </div>*@
        <div class="editor-label">
            @Html.LabelFor(model => model.UnitID)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.UnitID)
            @Html.ValidationMessageFor(model => model.UnitID)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.MaintenanceDate)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.MaintenanceDate)
            @Html.ValidationMessageFor(model => model.MaintenanceDate)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.UrgencyID, "UrgencyType")
        </div>
        <div class="editor-field">
            @Html.DropDownList("UrgencyID", String.Empty)
            @Html.ValidationMessageFor(model => model.UrgencyID)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.ServiceTypeID, "ServiceType")
        </div>
        <div class="editor-field">
            @Html.DropDownList("ServiceTypeID", String.Empty)
            @Html.ValidationMessageFor(model => model.ServiceTypeID)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.PetsinUnit)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.PetsinUnit)
            @Html.ValidationMessageFor(model => model.PetsinUnit)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.TenantPresence)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.TenantPresence)
            @Html.ValidationMessageFor(model => model.TenantPresence)
        </div>
        <div>
            <td>
                Partial Photo
                @Html.Partial("_MaintenancePhotoGalleryList", Model.MaintenancePhotoes)
            </td>
        </div>
        <p>
            <input type="submit" value="Save" />
        </p>
        @Html.HiddenFor(model => model.MaintenanceID)
    </fieldset>
}
<div>
    @Html.ActionLink("Add More Picture", "Index", "AddMaintenancePhoto", new { id = Model.MaintenanceID }, null)
</div>
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

RentalMVC2010/RentalMobile/Views/TenantMaintenance/Index.cshtml
@model List<RentalMobile.Models.MaintenanceOrder>
@{
    ViewBag.Title = "Home Page";
    Layout = "~/Views/Shared/Template/_ConceptLayoutPage.cshtml";
}
<h2>
    Index</h2>
<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            Request ID
        </th>
        <th>
            UnitID
        </th>
        <th>
            Date
        </th>
        <th>
            Urgency
        </th>
        <th>
            Description
        </th>
        <th>
            Service
        </th>
        <th>
            Pets
        </th>
        <th>
            TenantPresence
        </th>
        <th>
        </th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.MaintenanceID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UnitID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MaintenanceDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UrgencyType.UrgencyType1)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ServiceType.ServiceType1)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PetsinUnit)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TenantPresence)
            </td>
            <td>
                @Html.Partial("_MaintenancePhotoGallery", item.MaintenancePhotoes)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { Id = item.MaintenanceID }) |
                @Html.ActionLink("Details", "Details", new { Id = item.MaintenanceID }) |
                @Html.ActionLink("Delete", "Delete", new { Id = item.MaintenanceID }) |
            </td>
        </tr>
    }
</table>

RentalMVC2010/RentalMobile/Views/TenantMaintenance/_MaintenancePhotoGallery.cshtml
@model IEnumerable<RentalMobile.Models.MaintenancePhoto>
<table>
    @{
        if (Model.Any())
        {
            <tr>
                <td>
                    <img src="@Url.Content(Model.First().PhotoPath)" alt=""/>
                </td>
            </tr>
        }
        else
        {
            <tr>
                <td>
                    Empty Image
                </td>
            </tr>
        }
    }
</table>

RentalMVC2010/RentalMobile/Views/TenantMaintenance/_MaintenancePhotoGalleryList.cshtml
@model IEnumerable<RentalMobile.Models.MaintenancePhoto>


<table>
    <tr>
        <th>
            MaintenanceID
        </th>
        <th>
            PhotoID
        </th>
        <th>
            PhotoPath
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.MaintenanceID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PhotoID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PhotoPath)
            <img src="@Url.Content(item.PhotoPath)"/>
        </td>
       <td>
 
            @Html.ActionLink("Delete", "Delete", "MaintenancePhotoGallery", new { id = item.PhotoID }, null )
        </td>
    </tr>
}

</table>
<div class="containercontent">
    <div id="ImageContainer">
    </div>
    <div id="Uploader">
    </div>
    <div id="ImagePreview" >
        <img id="ImageView" />
    </div>
</div>

<script src="http://code.jquery.com/jquery-latest.min.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        var link;
        $('a.client-list').click(function () {
            link = $(this);
            $.ajax({
                url: '/MaintenancePhotoGallery/PopulateDetails?Id=5',
                dataType: 'json',
                success: function (data) {
                    $.each(data, function (id, val) {
                        alert(id.toString() + ' ' + val.toString());
                    });
                }
            });
            return false;
        });
    });
    </script>
@*<script>
    $(document).ready(function () { // initialize status bar

        function populateUserDetails() {
            var user = {};
            user.UserId = $("#UserId").val();
            $.getJSON("/MaintenancePhotoGallery/PopulateDetails/5", user, updateFields);
        };

        updateFields = function (data) {

            var test = data.LastName;
            alert(test);
//            $("#LastName").val(data.photoPath);
//            $("#FirstName").val(data.FirstName);
            $("#ImagePreview").html(data.photoPath);
        };
    });
</script>*@